# Generated by Django 2.1.7 on 2019-03-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='composition',
            name='coeficient',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composition',
            name='composition_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composition',
            name='product_reference_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='composition',
            name='unit',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composition',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='compositiongroup',
            name='composition',
            field=models.ManyToManyField(to='products.Composition'),
        ),
        migrations.AddField(
            model_name='composition',
            name='entity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.ReferenceEntity'),
            preserve_default=False,
        ),
    ]
