# Generated by Django 2.1.7 on 2019-03-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190309_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_id', models.CharField(max_length=20)),
                ('product_reference_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=20)),
                ('coeficient', models.DecimalField(decimal_places=4, max_digits=8)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ReferenceEntity')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='compositiongroup',
            name='composition',
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={},
        ),
        migrations.RemoveField(
            model_name='composition',
            name='coeficient',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='composition_id',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='product_reference_id',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='products',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='unit',
        ),
        migrations.DeleteModel(
            name='CompositionGroup',
        ),
        migrations.AddField(
            model_name='composition',
            name='composition',
            field=models.ManyToManyField(to='products.CompositionItem'),
        ),
    ]
